[build]
  # Build command for Astro
  command = "npm run build"
  # Directory to publish (the built files)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  # Ensure npm ci is used for faster, reliable builds
  NPM_FLAGS = "--prefer-offline --no-audit"
